spring.application.name=SmartCart_Ecommerce

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

project.image=images/
server.port=8081

spring.app.jwtSecret=${JWT_SECRET}
spring.app.jwtExpirationMs=${JWT_EXPIRATION_MS:3000000}
spring.app.jwtCookieName=${JWT_COOKIE_NAME:springBootEcom}
frontend.url=${FRONTEND_URL:https://smartcart.munashemudabura.com}
image.base.url=${IMAGE_BASE_URL:http://localhost:8081/images}

stripe.secret.key=${STRIPE_SECRET_KEY}

openai.api.key=${OPENAI_API_KEY}
openai.model=gpt-4o-mini
openai.api.url=https://api.openai.com/v1




#logging.level.org.springframework=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.springframework.security=DEBUG
#logging.level.com.ecommerce.project=DEBUG

